name: remilestone

on: [push]

jobs:
  remilestone-text-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: identify changed text files
        id: changed-text-files
        uses: tj-actions/changed-files@v29.0.1
        with:
          files_ignore: |
            **/*.yml
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.md
            **/*.inProgress
            **/*.py

      - name: no text files changed?
        if: steps.changed-text-files.outputs.any_changed == 'false'
        run: |
          echo "no text files changed"

      - name: install python
        if: steps.changed-text-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: install openiti library
        if: steps.changed-text-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install openiti

      - name: remilestone changed texts
        if: steps.changed-text-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-text-files.outputs.all_changed_files }}; do
            python .github/remilestone.py $file
            #echo $file
          done
         
      - name: commit any remilestoned text files
        if: steps.changed-text-files.outputs.any_changed == 'true'
        run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add -A
           git commit -m "remilestone changed files" -a
                
      - name: push any changes
        if: steps.changed-text-files.outputs.any_changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: main
